export { default as HomeLayout } from "./HomeLayout";
export { default as Register } from "./Register";
export { default as Login } from "./Login";
// export { default as Logout } from "./Logout";
export { default as DashboardLayout } from "./DashboardLayout";
export { default as ErrorElement } from "./ErrorElement";
export { default as DashboardLanding } from "./DashboardLanding";
export { default as AddNote } from "./AddNote";
export { default as ViewNotes } from "./ViewNotes";
export { default as EditNote } from "./EditNote";
// export { default as DeleteNote } from "./DeleteNote";
export { default as EditProfile } from "./EditProfile";
